# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\OneDrive\my_python\Qt\motor2d\multimotor0.2.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MotorScan(object):
    def setupUi(self, MotorScan):
        MotorScan.setObjectName("MotorScan")
        MotorScan.resize(711, 516)
        self.centralwidget = QtWidgets.QWidget(MotorScan)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.connect = QtWidgets.QPushButton(self.widget)
        self.connect.setObjectName("connect")
        self.horizontalLayout_2.addWidget(self.connect)
        self.home = QtWidgets.QPushButton(self.widget)
        self.home.setObjectName("home")
        self.horizontalLayout_2.addWidget(self.home)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.MotorChoice1 = QtWidgets.QComboBox(self.widget)
        self.MotorChoice1.setObjectName("MotorChoice1")
        self.gridLayout.addWidget(self.MotorChoice1, 0, 1, 1, 1)
        self.step1 = QtWidgets.QDoubleSpinBox(self.widget)
        self.step1.setSingleStep(0.1)
        self.step1.setProperty("value", 1.0)
        self.step1.setObjectName("step1")
        self.gridLayout.addWidget(self.step1, 0, 2, 1, 1)
        self.moveL1 = QtWidgets.QPushButton(self.widget)
        self.moveL1.setObjectName("moveL1")
        self.gridLayout.addWidget(self.moveL1, 0, 3, 1, 1)
        self.pos1 = QtWidgets.QDoubleSpinBox(self.widget)
        self.pos1.setObjectName("pos1")
        self.gridLayout.addWidget(self.pos1, 0, 4, 1, 1)
        self.moveR1 = QtWidgets.QPushButton(self.widget)
        self.moveR1.setObjectName("moveR1")
        self.gridLayout.addWidget(self.moveR1, 0, 5, 1, 1)
        self.stop1 = QtWidgets.QPushButton(self.widget)
        self.stop1.setObjectName("stop1")
        self.gridLayout.addWidget(self.stop1, 0, 6, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.MotorChoice2 = QtWidgets.QComboBox(self.widget)
        self.MotorChoice2.setObjectName("MotorChoice2")
        self.gridLayout.addWidget(self.MotorChoice2, 1, 1, 1, 1)
        self.step2 = QtWidgets.QDoubleSpinBox(self.widget)
        self.step2.setSingleStep(0.1)
        self.step2.setProperty("value", 1.0)
        self.step2.setObjectName("step2")
        self.gridLayout.addWidget(self.step2, 1, 2, 1, 1)
        self.moveL2 = QtWidgets.QPushButton(self.widget)
        self.moveL2.setObjectName("moveL2")
        self.gridLayout.addWidget(self.moveL2, 1, 3, 1, 1)
        self.pos2 = QtWidgets.QDoubleSpinBox(self.widget)
        self.pos2.setObjectName("pos2")
        self.gridLayout.addWidget(self.pos2, 1, 4, 1, 1)
        self.moveR2 = QtWidgets.QPushButton(self.widget)
        self.moveR2.setObjectName("moveR2")
        self.gridLayout.addWidget(self.moveR2, 1, 5, 1, 1)
        self.stop2 = QtWidgets.QPushButton(self.widget)
        self.stop2.setObjectName("stop2")
        self.gridLayout.addWidget(self.stop2, 1, 6, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.radius = QtWidgets.QDoubleSpinBox(self.widget)
        self.radius.setSingleStep(0.1)
        self.radius.setProperty("value", 0.5)
        self.radius.setObjectName("radius")
        self.horizontalLayout.addWidget(self.radius)
        self.StartScan = QtWidgets.QPushButton(self.widget)
        self.StartScan.setObjectName("StartScan")
        self.horizontalLayout.addWidget(self.StartScan)
        self.StopScan = QtWidgets.QPushButton(self.widget)
        self.StopScan.setObjectName("StopScan")
        self.horizontalLayout.addWidget(self.StopScan)
        self.NumRIters = QtWidgets.QSpinBox(self.widget)
        self.NumRIters.setMinimum(1)
        self.NumRIters.setMaximum(1000)
        self.NumRIters.setProperty("value", 100)
        self.NumRIters.setObjectName("NumRIters")
        self.horizontalLayout.addWidget(self.NumRIters)
        self.TimeStep = QtWidgets.QDoubleSpinBox(self.widget)
        self.TimeStep.setSingleStep(0.1)
        self.TimeStep.setProperty("value", 0.1)
        self.TimeStep.setObjectName("TimeStep")
        self.horizontalLayout.addWidget(self.TimeStep)
        self.NumIters = QtWidgets.QSpinBox(self.widget)
        self.NumIters.setProperty("value", 1)
        self.NumIters.setObjectName("NumIters")
        self.horizontalLayout.addWidget(self.NumIters)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.widget1 = QtWidgets.QWidget(self.splitter)
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.PosView = QtWidgets.QGraphicsView(self.widget1)
        self.PosView.setObjectName("PosView")
        self.horizontalLayout_3.addWidget(self.PosView)
        self.errors = QtWidgets.QTextBrowser(self.widget1)
        self.errors.setObjectName("errors")
        self.horizontalLayout_3.addWidget(self.errors)
        self.verticalLayout_2.addWidget(self.splitter)
        MotorScan.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MotorScan)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 711, 18))
        self.menubar.setObjectName("menubar")
        MotorScan.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MotorScan)
        self.statusbar.setObjectName("statusbar")
        MotorScan.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MotorScan)
        self.toolBar.setObjectName("toolBar")
        MotorScan.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(MotorScan)
        QtCore.QMetaObject.connectSlotsByName(MotorScan)

    def retranslateUi(self, MotorScan):
        _translate = QtCore.QCoreApplication.translate
        MotorScan.setWindowTitle(_translate("MotorScan", "MotorScan_v0.1"))
        self.connect.setText(_translate("MotorScan", "connect motors"))
        self.home.setText(_translate("MotorScan", "home motors"))
        self.label_4.setText(_translate("MotorScan", "step"))
        self.label_5.setText(_translate("MotorScan", "---"))
        self.label_6.setText(_translate("MotorScan", "position"))
        self.label_9.setText(_translate("MotorScan", "time step s"))
        self.label_8.setText(_translate("MotorScan", "N iterations"))
        self.label_2.setText(_translate("MotorScan", "motor 1"))
        self.moveL1.setText(_translate("MotorScan", "<<"))
        self.moveR1.setText(_translate("MotorScan", ">>"))
        self.stop1.setText(_translate("MotorScan", "stop"))
        self.label_3.setText(_translate("MotorScan", "motor 2"))
        self.moveL2.setText(_translate("MotorScan", "<<"))
        self.moveR2.setText(_translate("MotorScan", ">>"))
        self.stop2.setText(_translate("MotorScan", "stop"))
        self.label.setText(_translate("MotorScan", "radius mm"))
        self.StartScan.setText(_translate("MotorScan", "Start scan"))
        self.StopScan.setText(_translate("MotorScan", "Stop scan"))
        self.toolBar.setWindowTitle(_translate("MotorScan", "toolBar"))
